#!/usr/bin/env python3
"""Generate the two /reseller/ diagrams as translatable Liquid includes.

Writes `_includes/diagrams/partner-flow.svg` and `_includes/diagrams/white-label-layers.svg`.
THOSE FILES ARE GENERATED - edit this script and re-run, never the SVG.

Same blackboard style, and the same two reasons for it, as
`tools/make-topology-diagram.py` (read its header first - it is the original):

  * **Translation.** Every label is emitted as `{{ t.diagram_* }}`, so the strings live in
    `_data/i18n/en/reseller_partner.json` / `reseller_white_label.json` and vhtranslator
    carries them into every language. Text baked into an image would stay English.
  * **Fonts.** The page's own Poppins, self-hosted, because Google Fonts is blocked in CN.

The chalk look is two SVG filters, not artwork: `feTurbulence` + `feDisplacementMap` warps
every stroke off-true, and a second noise layer erodes stroke alpha into chalk dust. The
board keeps its dark ground in both themes on purpose - `.vh-topology-svg` in
`_sass/pages/_custom.scss` and `_sass/theme/_light.scss` already handle that, so both
diagrams reuse those classes rather than inventing new ones.

Each diagram states one idea and no more:

  partner-flow        the order goes down the chain and the key comes back up the same
                      chain; the customer only ever meets the partner's store. Our side is
                      drawn as "the VpnHood! STORE" because that is what a partner sees -
                      the Partner Hub is our implementation detail, not their vocabulary.
  white-label-layers  every sale, wherever it was made, lands in the partner's store,
                      which gets the key from us and hands it to the partner's own app.

Run from the repo root:  python tools/make-reseller-diagrams.py
"""
from __future__ import annotations

import math
import pathlib
import random

BOARD = "#22202f"
CHALK = "#ecebe3"
CHALK_DIM = "#a9a7b8"
MINT = "#9fe8d2"
VIOLET = "#c3b0ff"
AMBER = "#f2d9a2"

FONT = "&quot;Poppins&quot;, sans-serif"

# Seeded so the "hand-drawn" jitter is identical on every run - a rebuild must not produce
# a different file. Re-seeded per diagram so adding one never reshuffles the other.
rnd = random.Random(9)


def j(v: float, amt: float = 2.4) -> float:
    return v + rnd.uniform(-amt, amt)


def box(x, y, w, h, stroke=CHALK, sw=3.0, dash=None):
    d = ("M %.1f %.1f L %.1f %.1f L %.1f %.1f L %.1f %.1f Z"
         % (j(x), j(y), j(x + w), j(y), j(x + w), j(y + h), j(x), j(y + h)))
    da = ' stroke-dasharray="%s"' % dash if dash else ""
    return ('<path d="%s" fill="none" stroke="%s" stroke-width="%.1f" '
            'stroke-linejoin="round" stroke-linecap="round"%s/>' % (d, stroke, sw, da))


def stack(x, y, w, h, stroke, n=2, off=13):
    """Ghost outlines behind a box - "there are many of these" without drawing many."""
    return "".join(
        '<g opacity="%.2f">%s</g>' % (0.30 / i, box(x + off * i, y + off * i, w, h, stroke, 2.4))
        for i in range(n, 0, -1))


def txt(x, y, s, size=22, fill=CHALK, anchor="middle"):
    return ('<text x="%.1f" y="%.1f" font-family="%s" font-size="%d" fill="%s" '
            'text-anchor="%s">%s</text>' % (x, y, FONT, size, fill, anchor, s))


def arrow(x1, y1, x2, y2, stroke=MINT, sw=3.2, dash=None):
    d = "M %.1f %.1f L %.1f %.1f" % (j(x1, 1.6), j(y1, 1.6), x2, y2)
    da = ' stroke-dasharray="%s"' % dash if dash else ""
    ang = math.atan2(y2 - y1, x2 - x1)
    hl = 19
    h1 = (x2 - hl * math.cos(ang - 0.40), y2 - hl * math.sin(ang - 0.40))
    h2 = (x2 - hl * math.cos(ang + 0.40), y2 - hl * math.sin(ang + 0.40))
    return ('<path d="%s" fill="none" stroke="%s" stroke-width="%.1f" stroke-linecap="round"%s/>'
            '<path d="M %.1f %.1f L %.1f %.1f M %.1f %.1f L %.1f %.1f" fill="none" '
            'stroke="%s" stroke-width="%.1f" stroke-linecap="round"/>'
            % (d, stroke, sw, da, h1[0], h1[1], x2, y2, h2[0], h2[1], x2, y2, stroke, sw))


def render(out: str, data_file: str, en_var: str, w: int, h: int, uid: str, parts: list[str]) -> None:
    """Wrap the drawn parts in the board, the chalk filters and the Liquid preamble."""
    def t(key):
        return "{{ t.%s | default: %s.%s }}" % (key, en_var, key)

    svg = """<!-- GENERATED by tools/make-reseller-diagrams.py - do not edit; edit the script.
     Strings come from _data/i18n/<lang>/{DATA}.json via the page's `t` assign, each
     falling back to English so a not-yet-translated language never renders blank. -->
{{%- assign {EN} = site.data.i18n.en.{DATA} -%}}
<svg class="vh-topology-svg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}"
     role="img" aria-labelledby="{UID}Title {UID}Desc" preserveAspectRatio="xMidYMid meet">
  <title id="{UID}Title">{TITLE}</title>
  <desc id="{UID}Desc">{DESC}</desc>
  <defs>
    <filter id="{UID}Chalk" x="-6%" y="-6%" width="112%" height="112%">
      <feTurbulence type="fractalNoise" baseFrequency="0.028" numOctaves="3" seed="11" result="warp"/>
      <feDisplacementMap in="SourceGraphic" in2="warp" scale="4.2"
                         xChannelSelector="R" yChannelSelector="G" result="wobbly"/>
      <feTurbulence type="fractalNoise" baseFrequency="0.62" numOctaves="4" seed="5" result="grain"/>
      <feColorMatrix in="grain" type="matrix" result="grainA"
                     values="0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  .7 .4 .2 0 .05"/>
      <feComposite in="wobbly" in2="grainA" operator="in" result="eroded"/>
      <feMerge><feMergeNode in="eroded"/><feMergeNode in="eroded"/></feMerge>
    </filter>
    <filter id="{UID}Board" x="0" y="0" width="100%" height="100%">
      <feTurbulence type="fractalNoise" baseFrequency="0.75" numOctaves="4" seed="19" result="n"/>
      <feColorMatrix in="n" type="matrix"
                     values="0 0 0 0 .55  0 0 0 0 .54  0 0 0 0 .62  0 0 0 .05 0"/>
    </filter>
  </defs>

  <rect width="{W}" height="{H}" rx="18" fill="{BOARD}"/>
  <rect width="{W}" height="{H}" rx="18" filter="url(#{UID}Board)"/>

  <g filter="url(#{UID}Chalk)">
{PARTS}
  </g>
</svg>
""".format(W=w, H=h, BOARD=BOARD, UID=uid, DATA=data_file, EN=en_var,
           TITLE=t("diagram_title"), DESC=t("diagram_desc"),
           PARTS="\n".join("    " + p for p in parts))

    path = pathlib.Path("_includes/diagrams/%s.svg" % out)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(svg, encoding="utf-8")
    print("wrote %s (%d bytes)" % (path, len(svg)))


# ===========================================================================
# 1. partner-flow - down the chain to us, back up the same chain to the customer
# ===========================================================================
def partner_flow() -> None:
    global rnd
    rnd = random.Random(9)
    W, H = 900, 700
    T = lambda k: "{{ t.%s | default: vh_flow_en.%s }}" % (k, k)  # noqa: E731

    BW, BH, BX = 320, 116, 290      # shared box geometry
    CXX = BX + BW / 2
    DX, UX = CXX - 74, CXX + 74     # the order goes down the left lane, the code comes back up the right
    Y1, Y2, Y3 = 116, 316, 516      # customer / partner's store / us
    parts = []

    parts.append(txt(W / 2, 62, T("diagram_title"), size=30))

    # --- the partner's customer ------------------------------------------------
    parts.append(stack(BX, Y1, BW, BH, CHALK))
    parts.append(box(BX, Y1, BW, BH, CHALK, 3.2))
    parts.append(txt(CXX, Y1 + 52, T("diagram_customer"), size=25))
    parts.append(txt(CXX, Y1 + 82, T("diagram_customer_sub"), size=16, fill=CHALK_DIM))

    # --- the partner's store: the only thing the customer ever sees -------------
    parts.append(box(BX, Y2, BW, BH, VIOLET, 3.2))
    parts.append(txt(CXX, Y2 + 52, T("diagram_store"), size=25))
    parts.append(txt(CXX, Y2 + 82, T("diagram_store_sub"), size=16, fill=CHALK_DIM))
    parts.append(txt(BX - 26, Y2 + 62, T("diagram_yours"), size=19, fill=VIOLET, anchor="end"))

    # --- us: servers and codes, out of the customer's sight ----------------------
    parts.append(box(BX, Y3, BW, BH, MINT, 3.2))
    parts.append(txt(CXX, Y3 + 52, T("diagram_vpnhood"), size=25))
    parts.append(txt(CXX, Y3 + 82, T("diagram_vpnhood_sub"), size=16, fill=CHALK_DIM))
    parts.append(txt(BX - 26, Y3 + 62, T("diagram_ours"), size=19, fill=MINT, anchor="end"))

    # --- down: the order, left-hand lane ------------------------------------------
    parts.append(arrow(DX, Y1 + BH + 12, DX, Y2 - 14, stroke=CHALK, sw=3.0))
    parts.append(txt(DX - 18, Y1 + BH + 48, T("diagram_buys"), size=16, fill=CHALK_DIM, anchor="end"))
    parts.append(arrow(DX, Y2 + BH + 12, DX, Y3 - 14, stroke=VIOLET, sw=3.0))
    parts.append(txt(DX - 18, Y2 + BH + 40, T("diagram_orders"), size=16, fill=VIOLET, anchor="end"))
    parts.append(txt(DX - 18, Y2 + BH + 62, T("diagram_orders_sub"), size=15, fill=VIOLET, anchor="end"))

    # --- up: the code, right-hand lane, dashed like every "comes back" line ---------
    parts.append(arrow(UX, Y3 - 12, UX, Y2 + BH + 14, stroke=AMBER, sw=2.8, dash="12 9"))
    parts.append(txt(UX + 18, Y2 + BH + 52, T("diagram_key"), size=16, fill=AMBER, anchor="start"))
    parts.append(arrow(UX, Y2 - 12, UX, Y1 + BH + 14, stroke=AMBER, sw=2.8, dash="12 9"))
    parts.append(txt(UX + 18, Y1 + BH + 40, T("diagram_code"), size=16, fill=AMBER, anchor="start"))
    parts.append(txt(UX + 18, Y1 + BH + 62, T("diagram_code_sub"), size=15, fill=AMBER, anchor="start"))

    parts.append(txt(W / 2, H - 36, T("diagram_caption"), size=18, fill=AMBER))
    render("partner-flow", "reseller_partner", "vh_flow_en", W, H, "vhFlow", parts)


# ===========================================================================
# 2. white-label-layers - three ways to buy, one store, our codes, their app
# ===========================================================================
def white_label_layers() -> None:
    global rnd
    rnd = random.Random(21)
    W, H = 940, 790
    T = lambda k: "{{ t.%s | default: vh_layers_en.%s }}" % (k, k)  # noqa: E731
    parts = []

    parts.append(txt(W / 2, 58, T("diagram_title"), size=30))

    # --- where the customer buys: three doors into one store ----------------------
    TW, TH, TY = 230, 92, 118
    TXS = [60, 355, 650]
    parts.append(txt(W / 2, TY - 22, T("diagram_buy"), size=16, fill=CHALK_DIM))
    for x, key in zip(TXS, ("diagram_web", "diagram_play", "diagram_apple")):
        parts.append(box(x, TY, TW, TH, CHALK, 2.8))
        parts.append(txt(x + TW / 2, TY + 56, T(key), size=21))

    # --- the partner's store, the one place every order lands ----------------------
    SW, SH, SX, SY = 440, 110, 250, 318
    SCX = SX + SW / 2
    parts.append(box(SX, SY, SW, SH, VIOLET, 3.2))
    parts.append(txt(SCX, SY + 50, T("diagram_store"), size=25))
    parts.append(txt(SCX, SY + 80, T("diagram_store_sub"), size=16, fill=CHALK_DIM))
    parts.append(txt(SX + SW + 22, SY + 60, T("diagram_yours"), size=19, fill=VIOLET, anchor="start"))
    for x in TXS:
        parts.append(arrow(x + TW / 2, TY + TH + 12, SCX + (x + TW / 2 - W / 2) * 0.42, SY - 12,
                           stroke=CHALK, sw=2.6))

    # --- us, under the store's left half; the app, under its right half --------------
    LW, LH, LY = 320, 110, 566
    VX, AX = 90, 530
    parts.append(box(VX, LY, LW, LH, MINT, 3.2))
    parts.append(txt(VX + LW / 2, LY + 50, T("diagram_vpnhood"), size=25))
    parts.append(txt(VX + LW / 2, LY + 80, T("diagram_vpnhood_sub"), size=16, fill=CHALK_DIM))
    parts.append(txt(VX + LW / 2, LY + LH + 34, T("diagram_ours"), size=16, fill=MINT))

    parts.append(stack(AX, LY, LW, LH, CHALK))
    parts.append(box(AX, LY, LW, LH, CHALK, 3.2))
    parts.append(txt(AX + LW / 2, LY + 50, T("diagram_app"), size=25))
    parts.append(txt(AX + LW / 2, LY + 80, T("diagram_app_sub"), size=16, fill=CHALK_DIM))

    # store -> us (order) and us -> store (key): two lanes over the overlap
    parts.append(arrow(SX + 120, SY + SH + 12, SX + 120, LY - 14, stroke=VIOLET, sw=3.0))
    parts.append(txt(SX + 134, SY + SH + 58, T("diagram_orders"), size=15, fill=VIOLET, anchor="start"))
    parts.append(arrow(SX + 50, LY - 12, SX + 50, SY + SH + 14, stroke=AMBER, sw=2.8, dash="12 9"))
    parts.append(txt(SX + 36, SY + SH + 58, T("diagram_key"), size=15, fill=AMBER, anchor="end"))

    # store -> app: the customer signs in to the partner's store from the app and gets the key
    parts.append(arrow(AX + LW / 2, SY + SH + 12, AX + LW / 2, LY - 14, stroke=AMBER, sw=2.8, dash="12 9"))
    parts.append(txt(AX + LW / 2 + 16, SY + SH + 50, T("diagram_delivers"), size=15, fill=AMBER, anchor="start"))
    parts.append(txt(AX + LW / 2 + 16, SY + SH + 72, T("diagram_delivers_sub"), size=15, fill=AMBER, anchor="start"))

    parts.append(txt(W / 2, H - 36, T("diagram_caption"), size=18, fill=AMBER))
    render("white-label-layers", "reseller_white_label", "vh_layers_en", W, H, "vhLayers", parts)


partner_flow()
white_label_layers()
